baseURL = 'https://odhy-wedding-invitation.vercel.app/'
title = 'Anggi & Odhy - Wedding Invitation'

[module]
  [module.hugoVersion]
    extended = false
    min = "0.116.0"

[taxonomies]
  category = ""
  tag = ""
