baseURL = 'https://odhyp.github.io/wedding-invitation/'
languageCode = 'en-us'
title = 'Anggi & Odhy - Wedding Invitation'

[[menus.main]]
name = 'Home'
pageRef = '/'
weight = 10

[[menus.main]]
name = 'Posts'
pageRef = '/posts'
weight = 20

[[menus.main]]
name = 'Tags'
pageRef = '/tags'
weight = 30

[module]
  [module.hugoVersion]
    extended = false
    min = "0.116.0"
